name: FarmaJusta Deploy Pipeline

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main
            - develop
    workflow_dispatch:

jobs:
    Deploy-Development:
        if: github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Instalar Vercel CLI
              run: npm install --global vercel@latest

            - name: Bajar entorno DEV (Pull)
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Construir Proyecto (Build)
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Desplegar a DEV y Asignar URL Profesional
              run: |
                  DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
                  vercel alias set $DEPLOY_URL dev.farmanexo.com.pe --token=${{ secrets.VERCEL_TOKEN }} --scope farmajustas-projects

    Deploy-Production:
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Instalar Vercel CLI
              run: npm install --global vercel@latest

            - name: Bajar entorno PROD (Pull)
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Construir Proyecto (Build)
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Desplegar a PRODUCCIÓN
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
